### PR TITLE
Remove duplicate declaration and signing to itself

### PR DESCRIPTION
**Pull request by schlagmichdoch**

### CODE REVIEW

**Comment by oyooyo** [comment]
Thanks a lot for finding these little bugs, I seriously just wondered wtf I did there ;-)

**Comment by schlagmichdoch** [comment]
classic 😄 Actually my IDE told me these when I checked out what to do to make keyble more stable again. Any suggestions where to begin?

**Comment by oyooyo** [comment]
Nothing that immediately comes to my mind. I still assume that certain issues actually stem from the Bluetooth LE library that keyble uses but which got abandoned several years ago, but I do not know about any Bluetooth LE library for Node.js that could replace it.

**Comment by schlagmichdoch** [comment]
[According to the package.json](https://github.com/oyooyo/keyble/blob/master/package.json#L32) you switched to @abandonware/noble a while ago where [errors seem to be actively fixed](https://github.com/abandonware/noble/commits/master).
Do you think the library is buggy per se?

With **node-ble** there seems to be another ble library for node which has been actively developed since 2020:
[npmjs](https://www.npmjs.com/package/node-ble) [github repo](https://github.com/chrvadala/node-ble)

Any idea whether migrating would increase stability?

**Pull request merged**
